name: "update api docs"
on: [workflow_dispatch]
permissions: {}
jobs:
  update-api-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: "checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: "set up python"
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: .python-version
      - name: "generate and write api docs"
        run: python .github/scripts/update-api-docs.py
      - name: "create pull request"
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          delete-branch: true
          commit-message: "docs(api): rebuild new docs and write to API.md"
          title: "docs(api): rebuild and update docs"
          body: >
            New API.md has been generated using
            [update-api-docs.py](.github/scripts/update-api-docs.py).
